# 定义工作流名称，在 GitHub Actions 界面中显示为 "Run Yunpan Task"
name: Run Yunpan Task

# 定义工作流触发条件
on:
  schedule:
    # 定时触发：每天 UTC 时间 0 点（对应北京时间早 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 手动触发工作流的支持

# 定义作业
jobs:
  run-script:
    # 指定运行环境，这里使用 GitHub 提供的 Ubuntu 最新版本虚拟机
    runs-on: ubuntu-latest

    steps:
    # 第一步：检出代码
    - name: Checkout repository
      uses: actions/checkout@v3 # 使用 GitHub 官方的代码检出动作，将仓库代码下载到虚拟机

    # 第二步：设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v3 # 使用官方 Python 设置动作
      with:
        python-version: '3.12.4' # 指定 Python 版本为 3.12.4，可根据需要修改为其他版本

    # 第三步：安装依赖
    - name: Install dependencies
      run: | # 使用 Shell 脚本运行以下命令
        python -m pip install --upgrade pip # 升级 pip 到最新版本
        pip install requests schedule # 安装脚本运行所需的依赖包 requests 和 schedule

    # 第四步：设置环境变量并运行脚本
    - name: Run Yunpan Script
      run: | # 使用 Shell 脚本运行以下命令
        python 云盘云朵5.0.1.py # 执行上传的 Python 脚本
     # env:
       # ydypCk: ${{ secrets.YDYPCk }} # 将 GitHub Secrets 中配置的环境变量 YDYPCk 传递到脚本中
