name: Run Python Script

on:
  workflow_dispatch: # 手动触发工作流
  schedule:          # 定时运行（可选）
    - cron: '0 1 * * *' # 每天凌晨 1 点运行

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python 云盘云朵6.0.py
